app/aldynkushkash/urls.py
from django.contrib import admin
from django.contrib.flatpages import views
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('home/', include('home.urls', namespace='home')),
    path('news/', include('news.urls', namespace='news')),
    path('about/', views.flatpage, {'url': '/about/'}, name='about'),
    path('shop/', include('shop.urls', namespace='shop')),
    path('', include('protect.urls')),
    path('sign/', include('sign.urls')),
    path('accounts/', include('allauth.urls')),
]

app/home/urls.py
from django.urls import path
from .views import index


app_name = 'home'

urlpatterns = [
    path('', index, name='index'),
]

app/news/urls.py
from django.urls import path

from .views import PostListView, PostDetailView # , NewCreateView, NewUpdateView, NewDeleteView


app_name = 'news'

urlpatterns = [
    path('', PostListView.as_view(), name='post_list'),
    path('<int:pk>/', PostDetailView.as_view(), name='post_detail'),
    # path('create/', NewCreateView.as_view(), name='new_create'),
    # path('<int:pk>/update/', NewUpdateView.as_view(), name='new_update'),
    # path('<int:pk>/delete/', NewDeleteView.as_view(), name='new_delete'),

]

app/protect/urls.py
from django.urls import path
from .views import ProfileView

urlpatterns = [
    path('', ProfileView.as_view()),
]

app/shop/urls.py
from django.urls import path
from . import views


app_name = 'shop'

urlpatterns = [
    path('', views.product_list, name='product_list'),
    path('<int:id>/', views.product_detail, name='product_detail'),
    
]

app/sign/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView, LogoutView
from .views import BaseRegisterView, upgrade_me


urlpatterns = [
    path('login/', LoginView.as_view(template_name='sign/login.html'), name='login'),
    path('logout/', LogoutView.as_view(template_name='sign/logout.html'), name='logout'),
    path('signup/', BaseRegisterView.as_view(template_name='sign/signup.html'), name='signup'),
    path('upgrade/', upgrade_me, name='upgrade'),
]

app/home/models.py
from django.db import models

# Create your models here.

app/news/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone

from .utils import get_timestamp_path


class Author(models.Model):
    author = models.CharField(max_length=200)
    #user = models.OneToOneRel(User, on_delete=models.CASCADE)
    
    def __str__(self) -> str:
        return f'{self.author}'


class Post(models.Model):
    STATUS_CHOICES = (
        ('draft', 'Draft'),
        ('published', 'Published'),
    )
    title = models.CharField(max_length=256, verbose_name='Заголовок')
    author = models.ForeignKey(Author, on_delete=models.CASCADE, verbose_name='Автор')
    image = models.ImageField(blank=True, upload_to=get_timestamp_path, verbose_name='Изображение')
    text = models.TextField(verbose_name='Содержание')
    publish = models.DateTimeField(default=timezone.now())
    created = models.DateTimeField(auto_now_add=True)
    status = models.CharField(max_length=10, choices=STATUS_CHOICES, default='draft')
    
    def __str__(self) -> str:
        return f'{self.title}'
    
    class Meta:
        ordering = ('-publish',)
        
    

app/protect/models.py
from django.db import models

# Create your models here.

app/shop/models.py
from django.db import models
from django.urls import reverse


class Product(models.Model):
    name = models.CharField(max_length=256, db_index=True)
    slug = models.SlugField(max_length=256, db_index=True)
    description = models.TextField(blank=True)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    available = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    
    class Meta:
        ordering = ('name',)
        index_together = (('id', 'slug'),)
        verbose_name = 'Товар'
        verbose_name_plural = 'Товары'
        
    def __str__(self):
        return f'{self.name}'
    
    def get_absolute_url(self):
        return reverse('shop:product_detail', args=[self.id, self.slug])
    

app/sign/models.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User, Group
from allauth.account.forms import SignupForm
from django import forms


class BaseRegisterForm(UserCreationForm):
    email = forms.EmailField(label="Email")
    first_name = forms.CharField(label="Имя")
    last_name = forms.CharField(label="Фамилия")

    class Meta:
        model = User
        fields = ("username",
                  "first_name",
                  "last_name",
                  "email",
                  "password1",
                  "password2", )


class BasicSignupForm(SignupForm):

    def save(self, request):
        user = super(BasicSignupForm, self).save(request)
        basic_group = Group.objects.get(name='common')
        basic_group.user_set.add(user)
        return user
    

app/protect/forms.py
from django.forms import ModelForm
from django.contrib.auth.models import User


class UserForm(ModelForm):
    # в класс мета как обычно надо написать модель по которой будет строится форма и нужные нам поля.
    class Meta:
        model = User
        fields = '__all__'

app/home/views.py
from django.shortcuts import render

from news.models import Post


def index(request):
    posts = Post.objects.all()[:5]
    context = {'posts': posts}
    return render(request, 'home/index.html', context)

app/news/views.py
from django.contrib.auth import models
from django.db.models import query
from django.shortcuts import render

from django.views.generic import ListView, DetailView, UpdateView, CreateView, DeleteView

from .models import Post


class PostListView(ListView):
    model = Post
    template_name = 'news/post_list.html'
    context_object_name = 'posts'
    queryset = Post.objects.order_by('-created')
    paginate_by = 10
    
    def get_context_data(self, **kwargs):
        return super().get_context_data(**kwargs)
    

class PostDetailView(DetailView):
    template_name = 'news/post_detail.html'
    queryset = Post.objects.all()
    


    

app/protect/views.py
from django.contrib.auth.models import User
from django.views.generic import TemplateView, UpdateView
from django.contrib.auth.mixins import LoginRequiredMixin

from .forms import UserForm
from news.models import Post


class ProfileView(LoginRequiredMixin, TemplateView):
    template_name = 'protect/profile.html'
    # news = Post.objects.filter(author=request.user.pk)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['is_not_authors'] = not self.request.user.groups.filter(name='authors').exists()
        # context['news'] = self.news
        return context


class ProfileUpdateView(LoginRequiredMixin, UpdateView):
    template_name = 'protect/profile.html'
    form_class = UserForm
    success_url = '/'

app/shop/views.py
from django.shortcuts import render, get_object_or_404
from .models import Product
#from cart.forms import CartAddProductForm


def product_list(request):
    products = Product.objects.filter(available=True)
    # if category_slug:
    #     category = get_object_or_404(Category, slug=category_slug)
    #     products = products.filter(category=category)
    return render(request,
                  'shop/product_list.html',
                  {'products': products})


def product_detail(request, id, slug):
    product = get_object_or_404(Product, id=id, slug=slug, available=True)
    # cart_product_form = CartAddProductForm()

    return render(request, 'shop/product_detail.html', {'product': product})

app/sign/views.py
from django.contrib.auth.models import User, Group
from django.contrib.auth.decorators import login_required
from django.views.generic.edit import CreateView
from django.shortcuts import redirect

from .models import BaseRegisterForm


class BaseRegisterView(CreateView):
    model = User
    form_class = BaseRegisterForm
    success_url = '/'


@login_required
def upgrade_me(request):
    user = request.user
    authors_group = Group.objects.get(name='authors')
    if not request.user.groups.filter(name='authors').exists():
        authors_group.user_set.add(user)
    return redirect('/')

app/home/templates/home/index.html
{% extends "flatpages/default.html" %}

{% block title %}
    Главная
{% endblock title %}

{% block content %}
    Главная страинца
{% endblock content %}

app/news/templates/news/post_detail.html
{% extends "flatpages/default.html" %}

{% block title %}
    {{ post.title }}
{% endblock title %}

{% block content %}
    <div class="container-fluid mt-3">
        <div class="row">
            {% if post.image %}
                <div class="col-md-auto"><img class="main-image" src="#{{ post.image.url }}" alt="Изображение"></div>
            {% endif %}
            <div class="col">
                <h1>{{ post.title }}</h1>
                <p>{{ post.text }}</p>
                <a href="#"><u>Редактировать</u></a>
                <a href="#"><u> Удалить </u></a>
                <p class="text-right font-italic">Добавлено {{ post.created }}</p>
            </div>
        </div>
    </div>
{% endblock content %}

app/news/templates/news/post_list.html
{% extends 'flatpages/default.html' %}

{% block title %}
    Новости
{% endblock title %}

{% block content %}
    <h1>Новости Алдын-Кушкаш</h1>
    <a href="#">Добавить новую запись</a>
    <hr>
    {% if posts %}
        <ul class="list-unstyled">
            {% for post in posts %}
                <li class="media my-5 p-3 border">
                    <div>
                        <h2><a href="{% url 'news:post_detail' post.id %}">{{ post.title }}</a></h2>
                        <div>{{post.content | truncatewords:20 }}</div>
                        <p class="text-right font-italic">{{ post.created }}</p>
                    </div>
                </li>
            {% endfor %}
        </ul>
    {% else %}
        <h2>Нет новостей!</h2>
    {% endif %}
{% endblock content %}

app/protect/templates/protect/profile.html
{% extends 'flatpages/default.html' %}

{% block title %}
    Профиль {{request.user.username}}
{% endblock title %}

{% block content %}
    <h2>Страница авторизованного пользователя {{request.user.username}}</h2>
    <div> Здесь может содержаться персональная информация для каждого пользователя </div>



    <button> <a href="sign/logout/">Выйти</a> </button>
    {% if is_not_authors %}
      <button> <a href="sign/upgrade/"> Стать автором!</a> </button>
    {% endif %}
{% endblock %}

app/shop/templates/shop/product_detail.html
{% extends "shop/shop.html" %}

{% load static %}

{% block title %}
    {{ product.name }}
{% endblock title %}
    
{% block shopcontent %}
    <!-- Product section-->
    <section class="py-5">
        <div class="container px-4 px-lg-5 my-5">
            <div class="row gx-4 gx-lg-5 align-items-center">
                <div class="col-md-6"><img class="card-img-top mb-5 mb-md-0" src="https://dummyimage.com/600x700/dee2e6/6c757d.jpg" alt="..." /></div>
                <div class="col-md-6">
                    <div class="small mb-1">SKU: BST-498</div>
                    <h1 class="display-5 fw-bolder">Shop item template</h1>
                    <div class="fs-5 mb-5">
                        <span class="text-decoration-line-through">$45.00</span>
                        <span>$40.00</span>
                    </div>
                    <p class="lead">Lorem ipsum dolor sit amet consectetur adipisicing elit. Praesentium at dolorem quidem modi. Nam sequi consequatur obcaecati excepturi alias magni, accusamus eius blanditiis delectus ipsam minima ea iste laborum vero?</p>
                    <div class="d-flex">
                        <input class="form-control text-center me-3" id="inputQuantity" type="num" value="1" style="max-width: 3rem" />
                        <button class="btn btn-outline-dark flex-shrink-0" type="button">
                            <i class="bi-cart-fill me-1"></i>
                            Add to cart
                        </button>
                    </div>
                </div>
            </div>
        </div>
    </section>
{% endblock shopcontent %}

app/shop/templates/shop/product_list.html
{% extends "shop/shop.html" %}

{% block title %}
    Магазин
{% endblock title %}

{% block shopcontent %}
    <!-- Related items section-->
    <section class="py-5 bg-light">
        <div class="container px-4 px-lg-5 mt-5">
            <h2 class="fw-bolder mb-4">Related products</h2>
            <div class="row gx-4 gx-lg-5 row-cols-2 row-cols-md-3 row-cols-xl-4 justify-content-center">
                <div class="col mb-5">
                    <div class="card h-100">
                        <!-- Product image-->
                        <img class="card-img-top" src="https://dummyimage.com/450x300/dee2e6/6c757d.jpg" alt="..." />
                        <!-- Product details-->
                        <div class="card-body p-4">
                            <div class="text-center">
                                <!-- Product name-->
                                <h5 class="fw-bolder">{{ product.name }}</h5>
                                <!-- Product price-->
                                $40.00 - $80.00
                            </div>
                        </div>
                        <!-- Product actions-->
                        <div class="card-footer p-4 pt-0 border-top-0 bg-transparent">
                            <div class="text-center"><a class="btn btn-outline-dark mt-auto" href="{{ product.get_absolute_url }}">View options</a></div>
                        </div>
                    </div>
                </div>
                <div class="col mb-5">
                    <div class="card h-100">
                        <!-- Sale badge-->
                        <div class="badge bg-dark text-white position-absolute" style="top: 0.5rem; right: 0.5rem">Sale</div>
                        <!-- Product image-->
                        <img class="card-img-top" src="https://dummyimage.com/450x300/dee2e6/6c757d.jpg" alt="..." />
                        <!-- Product details-->
                        <div class="card-body p-4">
                            <div class="text-center">
                                <!-- Product name-->
                                <h5 class="fw-bolder">Special Item</h5>
                                <!-- Product reviews-->
                                <div class="d-flex justify-content-center small text-warning mb-2">
                                    <div class="bi-star-fill"></div>
                                    <div class="bi-star-fill"></div>
                                    <div class="bi-star-fill"></div>
                                    <div class="bi-star-fill"></div>
                                    <div class="bi-star-fill"></div>
                                </div>
                                <!-- Product price-->
                                <span class="text-muted text-decoration-line-through">$20.00</span>
                                $18.00
                            </div>
                        </div>
                        <!-- Product actions-->
                        <div class="card-footer p-4 pt-0 border-top-0 bg-transparent">
                            <div class="text-center"><a class="btn btn-outline-dark mt-auto" href="#">Add to cart</a></div>
                        </div>
                    </div>
                </div>
                <div class="col mb-5">
                    <div class="card h-100">
                        <!-- Sale badge-->
                        <div class="badge bg-dark text-white position-absolute" style="top: 0.5rem; right: 0.5rem">Sale</div>
                        <!-- Product image-->
                        <img class="card-img-top" src="https://dummyimage.com/450x300/dee2e6/6c757d.jpg" alt="..." />
                        <!-- Product details-->
                        <div class="card-body p-4">
                            <div class="text-center">
                                <!-- Product name-->
                                <h5 class="fw-bolder">Sale Item</h5>
                                <!-- Product price-->
                                <span class="text-muted text-decoration-line-through">$50.00</span>
                                $25.00
                            </div>
                        </div>
                        <!-- Product actions-->
                        <div class="card-footer p-4 pt-0 border-top-0 bg-transparent">
                            <div class="text-center"><a class="btn btn-outline-dark mt-auto" href="#">Add to cart</a></div>
                        </div>
                    </div>
                </div>
                <div class="col mb-5">
                    <div class="card h-100">
                        <!-- Product image-->
                        <img class="card-img-top" src="https://dummyimage.com/450x300/dee2e6/6c757d.jpg" alt="..." />
                        <!-- Product details-->
                        <div class="card-body p-4">
                            <div class="text-center">
                                <!-- Product name-->
                                <h5 class="fw-bolder">Popular Item</h5>
                                <!-- Product reviews-->
                                <div class="d-flex justify-content-center small text-warning mb-2">
                                    <div class="bi-star-fill"></div>
                                    <div class="bi-star-fill"></div>
                                    <div class="bi-star-fill"></div>
                                    <div class="bi-star-fill"></div>
                                    <div class="bi-star-fill"></div>
                                </div>
                                <!-- Product price-->
                                $40.00
                            </div>
                        </div>
                        <!-- Product actions-->
                        <div class="card-footer p-4 pt-0 border-top-0 bg-transparent">
                            <div class="text-center"><a class="btn btn-outline-dark mt-auto" href="#">Add to cart</a></div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
{% endblock shopcontent %}

app/shop/templates/shop/shop.html
{% extends "flatpages/default.html" %}

{% load static %}

{% block title %}Магазин{% endblock %}

{% block content %}
    <div class="cart">
        <div class="container px-4 px-lg-5">
            <a class="navbar-brand" href="/">Магазин Алдын-Кушкаш</a>
            <form class="d-flex">
                <button class="btn btn-outline-dark" type="submit">
                    <i class="bi-cart-fill me-1"></i>
                    Корзина
                    <span class="badge bg-dark text-white ms-1 rounded-pill">0</span>
                </button>
            </form>
        </div>
    </div>
    <!-- <div id="subheader">
        <div class="cart">
            {% with total_items=cart|length %}
                {% if total_items > 0 %}
                    Your cart:
                    <a href="{% url 'cart:cart_detail' %}">
                        {{ total_items }} item{{ total_items|pluralize }},
                        ${{ cart.get_total_price }}
                    </a>
                {% else %}
                    Your cart is empty.
                {% endif %}
            {% endwith %}
        </div>
    </div> -->
    <div id="content">
        {% block shopcontent %}
        {% endblock shopcontent %}
    </div>
{% endblock content %}

app/sign/templates/sign/login.html
{% extends 'flatpages/default.html' %}

{% block content %}
    <h2> Войти в систему </h2>
    <form method="post" action="{% url 'login' %}">
        {% csrf_token %}
            <table>
            <tr>
                <td>{{ form.username.label_tag }}</td>
                <td>{{ form.username }}</td>
            </tr>
            <tr>
                <td>{{ form.password.label_tag }}</td>
                <td>{{ form.password }}</td>
            </tr>
        </table>

        <input type="submit" value="Войти">
    </form>
    <button> <a href="/sign/signup"> Регистрация </a></button>
{% endblock %}

app/sign/templates/sign/logout.html
{% extends 'flatpages/default.html' %}

{% block content %}
    <h2> Вы вышли из системы. </h2>

{% endblock %}

app/sign/templates/sign/signup.html
{% extends 'flatpages/default.html' %}

{% block content %}
    <h2> Войти в систему </h2>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Продолжить">
    </form>
{% endblock %}

app/templates/base.html
from django.contrib import admin


<!DOCTYPE html>
<html>
    <head>
        <title>{% block head_title %}{% endblock head_title %}</title>
    </head>
    <body>
        {% block body %}
        {% block content %}
        {% endblock content %}
        {% endblock body %}
        {% block extra_body %}
        {% endblock extra_body %}
    </body>
</html>